name: Hostname Redirect
version: 0.1a
main: me.azenet.HR.HostnameRedirect
author: azenet
description: Redirect guys to world/position
commands:
    hr:
        usage: /hr <command>
        description: Choix d'un kit